### ISSUE TITLE
fingerprinted urls in production

### ISSUE THREAD

**Issue by avalez** [Tug/express-asset-manager#4]
Hi Tug,

First of all thank you for great library, it works great for optimizing static content in production.

Though, it looks like it's missing relevant functionality to generate fingerprinted files and urls in production. I think built assets should be named with fingerprints, and asset url be accordingly fingerprinted, e.g.;

    <script src="/assets/js/a6edcf683bc4df33bb82ae1cca3cf21a-app.js" type="text/javascript"></script>

Then builtAssets dir could be served with max possible age, or easily used with CDN.

Thoughts?

Thank you.

**Comment by Tug** [comment]
Feature added in last version 0.3

**Comment by Tug** [comment]
As a sidenote, this currently does not work with require.js, only for assets of type `js`.

**Comment by avalez** [comment]
Works for me! Thank you so much!
